name: Generate Sitemap

on:
  push:
    branches:
      - main  # or "master" if that's your default branch

permissions:
  contents: write   # allow pushing commits

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate sitemap
        run: python3 sitemap_generator.py

      - name: Commit updated sitemap
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "[bot] Auto-update sitemap ($(date +'%Y-%m-%d'))" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
