name: Generate Sitemap

on:
  push:
    branches:
      - main  # or your default branch (check if your repo uses 'main' or 'master')

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate sitemap
        run: python3 sitemap_generator.py

      - name: Commit updated sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Auto-update sitemap" || echo "No changes to commit"
          git push

